#!/bin/bash

# need git to get code
pkgin -y in scmgit

cd /root
git clone git://github.com/nshalman/qemu-smartos-build.git
mv qemu-smartos-build/* /root/
tar -C / -xzf /root/onbld.tar.gz
bash build-spiced-qemu.bash
