#!/bin/bash

sm-summary | grep -q "base64 13.1.0" || { echo "Only the base64 13.1.0 is currently supported for building" ; exit 1 ;}

# need git to get code
pkgin up && pkgin -y in scmgit
cd /root
git clone git://github.com/nshalman/qemu-smartos-build.git
cd qemu-smartos-build
./do
